before_script: # 定义在job执行之前的执行脚本(就一次)
  - echo "hello gitlab ci"

stages: # 定义Pipeline的阶段，可以多个
  - build
  - test
  - deploy

build_job: # 定义一个job
  stage: build # 设置job所属的stage，默认是test
  tags:  # 定义tags，用来匹配相应的Runner来执行
    - my-tag
  script: # 定义后面Runner来执行的具体脚本
    - cd /root/test
    - git pull
    - npm install

test_job:
  stage: test
  tags:
    - my-tag
  script:
    - cd /root/test
    - npm test

deploy_job:
  stage: deploy
  tags:
    - my-tag
  script:
    - cd /root/test
    - npm start &